version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - "8002:8000"
    env_file:
      - docker/env/.env
      - docker/env/.db.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.0-alpine
    hostname: chat_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/env/.db.env
  redis:
    image: redis:latest
    restart: always

volumes:
  postgres_data:
